### ISSUE TITLE
getAuthToken doesn't work

### ISSUE THREAD

**Issue by Rainson12** [polychrom/cordova-android-accountmanager#11]
Hey,
first of all - nice work. Thanks for contributing this plugin. I found a bug and as I have limited Java knowledge I would like to ask for a solution or workarround:

in AccountManagerPlugin.java (line 286) the overloaded arguments are checked for availability (argument 0, arg1 and arg3). Argument 2 isn't checked and also not used? 
also the js file (accountmanager.js line 61) only 2 parameters will be overloaded ([account, authTokenType]). I changed the overloading to
[account, authTokenType, null, true] but now i receive an error in the callback with "JSON error".

Any suggestions are appreciated.

**Comment by mafcm** [comment]
I have the same problem

**Comment by pierrejochem** [comment]
Me too :worried:

**Comment by pierrejochem** [comment]
Found the error. See here:

https://github.com/polychrom/cordova-android-accountmanager/pull/13/commits/09311524bb09d695f8b587c709c4f2ec7e24a713

There is also another bug which is corrected here:

https://github.com/polychrom/cordova-android-accountmanager/pull/12/commits/f0222c6e6390298cd3fbe5187c5f2cbdb3616ab3

After that it works like a champ

**Comment by pierrejochem** [comment]
The above pull requests are merged into master now.
