### ISSUE TITLE
Access denied on addAccountExplicitly

### ISSUE THREAD

**Issue by ggozad** [polychrom/cordova-android-accountmanager#8]
Hey,
While testing the plugin, I am getting an "Access denied" error when calling ``addAccountExplicitly``.
This is on a fresh app containing only the plugin. 

       var am = window.plugins.accountmanager;

        // Add account explicitly

        am.getAccountsByType('io.cordova.hellocordova.TestType', function(error, accounts)
        {
            console.log(error);
            accounts.forEach(function(account)
            {
                console.log('Account: ' + JSON.stringify(account));
            });
        });

       am.addAccountExplicitly('io.cordova.hellocordova.TestType', 'test', 'password', {email: 'test@testdomain.com'}, function(error, bob)
        {
            console.log(error);
            console.log(bob.id);
            console.log(JSON.stringify(bob));
        });

I can see in AndroidManifest.xml that the permission are requested as this is installed using the automatic cordova plugin installation.
Any hints?

**Comment by ggozad** [comment]
After making the exception handling return the stacktrace, I can see that this has to do with a mismatch of the account type and the type defined in ``authenticator.xml``. What is the proper way of handling this? Can I configure it through config.xml?

**Comment by mwheeler** [comment]
I've updated authenticator.xml to refer to `@string/aam_account_type`, so you should be able to add a `<string name="aam_account_type">MyAccountType</string>` to res/values/strings.xml (which is now the default on a fresh install), where the first argument to addAccountExplicitly is "MyAccountType".

I also updated documentation and the example app to reflect.
Let me know if you still have problems.

**Comment by ggozad** [comment]
No this is perfect. I had already prepared a PR for similar... Thank you!

**Comment by nuschz** [comment]
Hey there, 
i am getting the same issue, although i have just installed the plugin through the cordova CLi.
I can see the above mentioned <string name="aam_account_type">MyAccountType</string>  in the strings.xml file.
Here is my code: 

var am = window.plugins.accountmanager;

		// Add account explicitly
		am.addAccountExplicitly("test", "user", "pwd", null, function(error, bob)
		{
//			alert("adding account " + systemName.getValue());
			if(error){
				alert("onCreate "+error);
				return;
			}else if (bob){
				alert("onCreate "+ bob);
				return;
			}
			alert("success");
});

Regards,
Georgi

**Comment by SayNoToBassism** [comment]
Hi,
where do I have to put my `<string name="aam_account_type">AnotherAccountType</string>`?

> I also updated documentation and the example app to reflect.

I didn't find that point in the documentation or the example app.

Can you give me a clue? :-)

**Comment by pierrejochem** [comment]
Hi @SayNoToBassism 

How have you installed the plugin?

**Comment by SayNoToBassism** [comment]
Where is this code located? Do I have to modify a specific XML or create one?

By now, I can only find the original code in
_/plugins/com.polychrom.cordova.AccountManagerPlugin/plugin.xml_
which - I assume - should not be modified (?) and the generated / merged result in
_/platforms/android/res/values/strings.xml_

What is the correct place to put my customization?

**Comment by pierrejochem** [comment]
**platforms/android/res/values/strings.xml** is the correct place and yes do not change it in the plugin.xml.

**Comment by SayNoToBassism** [comment]
I already tried that but I get this message on build/run:
_Error: Found item String/aam_account_type more than one time_

In the strings.xml, the key aam_account_type is now in 2 lines:
```
<string name="aam_account_type">AnotherAccountType</string>
<string name="aam_account_type">MyAccountType</string>
```

**Comment by pierrejochem** [comment]
Have you manual edit files inside the plugin folder?

**Comment by SayNoToBassism** [comment]
No, I also re-installed it now but with the same result.

**Comment by pierrejochem** [comment]
Please some steps to reproduce

**Comment by SayNoToBassism** [comment]
For the re-install, I did:
`cordova plugin remove com.polychrom.cordova.AccountManagerPlugin
cordova plugin add https://github.com/polychrom/cordova-android-accountmanager.git`

Then I added
`<string name="aam_account_type">AnotherAccountType</string>`
to platforms/android/res/values/strings.xml and started run/build for Android.
Now I get the "duplicate entry" error.

**Comment by pierrejochem** [comment]
<string name="aam_account_type">AnotherAccountType</string> is added by `cordova plugin add` due to the plugin.xml definition. So no need to do it manual. Only change the value on demand after adding the plugin.

**Comment by SayNoToBassism** [comment]
I am using PhpStorm 2016.2.1 and Cordova 6.3.1

If I simply change the value in strings.xml (which I did when I initially installed the plugin), the original line
`<string name="aam_account_type">MyAccountType</string>`
will also be _blindly_ copied by some merger tool to strings.xml, thus producing the error.

Where does the merger pick this "old" value?

**Comment by pierrejochem** [comment]
This is called from the add-plugin-function:

`<config-file target="res/values/strings.xml" parent="/*">
        <string name="aam_account_type">MyAccountType</string>
</config-file>`

Are you installing all plugins every time you build or run the project?

**Comment by SayNoToBassism** [comment]
The IDE protocol says on build:
`[phonegap] executing 'cordova run android ' ...`
`[phonegap] completed 'cordova run android --no-telemetry'`
I wouldn't assume that the plugin is re-installed on every build, and as I haven't changed any corresponding settings, the default behaviour of the build batch should apply.

I added some dots to the plugin's LICENSE text file to see if it is re-installed, but the changes didn't revert. So it doesn't look like a re-install to me ;-)

**Comment by pierrejochem** [comment]
I will check the documentation. Maybe there is a way to prevent this behaviour.

https://cordova.apache.org/docs/de/latest/plugin_ref/spec.html
